#!/bin/sh -e
# postrm script for Schimpf SQL Library

case "$1" in
	remove)
		# eliminamos el enlace existente
		[ -e /usr/share/java/schimpf-mysql.jar ] && rm -f /usr/share/java/schimpf-mysql.jar
		[ -e /usr/share/java/schimpf-postgresql.jar ] && rm -f /usr/share/java/schimpf-postgresql.jar
		;;
	
	upgrade)
		;;

	abort-install|abort-upgrade|failed-upgrade)
		;;

	disappear)
		;;

	purge)
		;;

	*)
		echo "postrm called with unknown argument $1" >&2
		exit 1
		;;
esac