#!/bin/sh -e
# prerm script for Schimpf All Libraries

case "$1" in
	remove | upgrade)
		;;

	deconfigure)
		;;

	failed-upgrade)
		;;

	*)
		echo "prerm called with unknown argument $1" >&2
		exit 1
		;;
esac