#!/bin/sh -e
# postrm script for Schimpf Java Library

case "$1" in
	remove)
		# eliminamos el enlace existente
		[ -e /usr/share/java/schimpf-tail-file.jar ] && rm -f /usr/share/java/schimpf-tail-file.jar
		[ -e /usr/share/java/schimpf-threads-manager.jar ] && rm -f /usr/share/java/schimpf-threads-manager.jar
		[ -e /usr/share/java/schimpf-compiler.jar ] && rm -f /usr/share/java/schimpf-compiler.jar
		[ -e /usr/share/java/schimpf-jar-updater.jar ] && rm -f /usr/share/java/schimpf-jar-updater.jar
		;;
	
	upgrade)
		;;

	abort-install|abort-upgrade|failed-upgrade)
		;;

	disappear)
		;;

	purge)
		;;

	*)
		echo "postrm called with unknown argument $1" >&2
		exit 1
		;;
esac