#!/bin/bash

DIR=`dirname "$0"`
cd "$DIR"
ant -Dbasedir=../Trunk -f ../Trunk/util/build.xml
ant -Dbasedir=../Trunk -f ../Trunk/awt/build.xml
ant -Dbasedir=../Trunk -f ../Trunk/java/build.xml
ant -Dbasedir=../Trunk -f ../Trunk/net/build.xml
ant -Dbasedir=../Trunk -f ../Trunk/sql/build.xml