#!/bin/sh -e
# postinst script for Schimpf Util Library

case "$1" in
	configure)
		# eliminamos el enlace existente
		[ -e /usr/share/java/schimpf-sortablelist.jar ] && rm -f /usr/share/java/schimpf-sortablelist.jar
		[ -e /usr/share/java/schimpf-sortablelist-multithreaded.jar ] && rm -f /usr/share/java/schimpf-sortablelist-multithreaded.jar
		[ -e /usr/share/java/schimpf-abrupt-crypter.jar ] && rm -f /usr/share/java/schimpf-abrupt-crypter.jar
		[ -e /usr/share/java/schimpf-base64-crypter.jar ] && rm -f /usr/share/java/schimpf-base64-crypter.jar
		[ -e /usr/share/java/schimpf-exceptions.jar ] && rm -f /usr/share/java/schimpf-exceptions.jar
		
		# generamos el enlace
		ln -s /usr/lib/schimpf/libschimpf-util.jar /usr/share/java/schimpf-sortablelist.jar
		ln -s /usr/lib/schimpf/libschimpf-util.jar /usr/share/java/schimpf-sortablelist-multithreaded.jar
		ln -s /usr/lib/schimpf/libschimpf-util.jar /usr/share/java/schimpf-abrupt-crypter.jar
		ln -s /usr/lib/schimpf/libschimpf-util.jar /usr/share/java/schimpf-base64-crypter.jar
		ln -s /usr/lib/schimpf/libschimpf-util.jar /usr/share/java/schimpf-exceptions.jar
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument $1" >&2
		exit 1
		;;
esac