#!/bin/sh -e
# postinst script for Schimpf Net Library

case "$1" in
	configure)
		# eliminamos el enlace existente
		[ -e /usr/share/java/schimpf-ssh.jar ] && rm -f /usr/share/java/schimpf-ssh.jar
		[ -e /usr/share/java/schimpf-email.jar ] && rm -f /usr/share/java/schimpf-email.jar
		[ -e /usr/share/java/schimpf-sockets.jar ] && rm -f /usr/share/java/schimpf-sockets.jar.jar
		[ -e /usr/share/java/schimpf-connection-data.jar ] && rm -f /usr/share/java/schimpf-connection-data.jar
		
		# genramos los enlaces
		ln -s /usr/lib/schimpf/libschimpf-net.jar /usr/share/java/schimpf-ssh.jar
		ln -s /usr/lib/schimpf/libschimpf-net.jar /usr/share/java/schimpf-email.jar
		ln -s /usr/lib/schimpf/libschimpf-net.jar /usr/share/java/schimpf-sockets.jar
		ln -s /usr/lib/schimpf/libschimpf-net.jar /usr/share/java/schimpf-connection-data.jar
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument $1" >&2
		exit 1
		;;
esac