#!/bin/sh -e
# postrm script for Schimpf Net Library

case "$1" in
	remove)
		# eliminamos el enlace existente
		[ -e /usr/share/java/schimpf-ssh.jar ] && rm -f /usr/share/java/schimpf-ssh.jar
		[ -e /usr/share/java/schimpf-email.jar ] && rm -f /usr/share/java/schimpf-email.jar
		[ -e /usr/share/java/schimpf-sockets.jar ] && rm -f /usr/share/java/schimpf-sockets.jar.jar
		[ -e /usr/share/java/schimpf-connection-data.jar ] && rm -f /usr/share/java/schimpf-connection-data.jar
		;;
	
	upgrade)
		;;

	abort-install|abort-upgrade|failed-upgrade)
		;;

	disappear)
		;;

	purge)
		;;

	*)
		echo "postrm called with unknown argument $1" >&2
		exit 1
		;;
esac