#!/bin/sh -e
# postrm script for Schimpf SQL Library

case "$1" in
	remove)
		# eliminamos el enlace existente
		rm -f /usr/share/java/org.schimpf.sql.jar
		;;
	
	upgrade)
		;;

	abort-install|abort-upgrade|failed-upgrade)
		;;

	disappear)
		;;

	purge)
		;;

	*)
		echo "postrm called with unknown argument $1" >&2
		exit 1
		;;
esac