#!/bin/sh -e
# postinst script for Schimpf AWT Library

case "$1" in
	configure)
		# eliminamos el enlace existente
		[ -e /usr/share/java/schimpf-window.jar ] && rm -f /usr/share/java/schimpf-window.jar
		# generamos el enlace
		ln -s /usr/lib/schimpf/libschimpf-awt.jar /usr/share/java/schimpf-window.jar
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument $1" >&2
		exit 1
		;;
esac