#!/bin/sh -e
# postrm script for Schimpf AWT Library

case "$1" in
	remove)
		# eliminamos el enlace existente
		[ -e /usr/share/java/schimpf-window.jar ] && rm -f /usr/share/java/schimpf-window.jar
		;;
	
	upgrade)
		;;

	abort-install|abort-upgrade|failed-upgrade)
		;;

	disappear)
		;;

	purge)
		;;

	*)
		echo "postrm called with unknown argument $1" >&2
		exit 1
		;;
esac