#!/bin/sh -e
# postinst script for Schimpf AWT Library

case "$1" in
	configure)
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument $1" >&2
		exit 1
		;;
esac